[project]
name = "Typhon"
version = "0.1.0"
description = "Typhon programming language"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pegen>=0.3.0",
    "pyright>=1.1.403",
    "pytest>=8.4.1",
    "ruff>=0.12.5",
]
