[project]
name = "uv-pegen-example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pegen>=0.3.0",
    "pyright>=1.1.403",
    "ruff>=0.12.5",
]
